### ISSUE TITLE
pip install git+... under python3 with LANG=ascii breaks.

### ISSUE THREAD

**Issue by kezabelle** [kezabelle/django-haystackbrowser#14]
Originally encountered by @jannon in their fork at 587462ae343d5ba8fbf079b2f3bc7ba6d0d3245e.

Can reproduce locally by doing the following:
```
pyenv global 3.5.1
mktmpenv
export LANG='ascii'
pip install -e git+git@github.com:kezabelle/django-haystackbrowser.git#egg=django-haystackbrowser
```
yields:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/kez/Virtualenvs/tmp-610bf7dac88935a/src/django-haystackbrowser/setup.py", line 57, in <module>
        LONG_DESCRIPTION = "\r\n\r\n----\r\n\r\n".join(make_readme(HERE))
      File "/Users/kez/Virtualenvs/tmp-610bf7dac88935a/src/django-haystackbrowser/setup.py", line 51, in make_readme
        yield f.read()
      File "/Users/kez/.pyenv/versions/3.5.1/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 927: ordinal not in range(128)
```

Doing the same with `LANG='en_GB.UTF-8'` works fine.

The original commit can't be pulled in wholesale because open() doesn't take `encoding` in CPython2.
Probably could do it by checking something like:
```
if sys.version_info[0] == 2:
    # get the Py3K compatible `encoding=` for opening files.
    from io import open
```
Will experiment.

**Comment by kezabelle** [comment]
Should hopefully be resolved by commits:
cf02e83cb4de388d98cbb73777aa952d0eac24e9
aa41df72a9b1507bd92d772d12a9f38c2361e390
d47857efbf596333c3ba346f3c30f5aaa51f8fee
8e763c73ab87906467c415e27132d0772a3f70f5
a12f4d7fa685566e4de3616c511f7d52729d4e6b
7414f38d53afb03a025c92ca21ffa5f9fc538480
Most specifically, 7414f38d53afb03a025c92ca21ffa5f9fc538480
